# -*- coding: utf-8 -*-
"""NABIS공모전.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FkuyOxiw_F7E8eLOXdb5M62Ft5yIHCmd
"""

# 한글 패치
!sudo apt-get install -y fonts-nanum

!sudo fc-cache -fv

!rm ~/.cache/matplotlib -rf

# 구글 드라이브 데이터 불러오기
from google.colab import drive
drive.mount('/content/drive')

# 경찰 담당 주민 수 파일 가져오기
import pandas as pd
residents = '/content/drive/MyDrive/2023NABIS공모전/경찰공무원 1인당 담당주민수(시도)_2021.xlsx'

# CSV 파일 읽어오기
residents = pd.read_excel(residents)

# 가져온 데이터를 확인
residents

# residents 데이터의 0행 삭제
residents.drop(0, inplace=True)
residents

# residents 데이터의 0열 삭제
residents.drop('경찰공무원 1인당 담당주민수(시도)', axis=1, inplace=True)
residents

# 특정 컬럼의 이름 변경
residents.rename(columns={'Unnamed: 1': '지역'}, inplace=True)
residents.rename(columns={'Unnamed: 2': '경찰공무원 1인당 담당주민수(A/B)'}, inplace=True)
residents.rename(columns={'Unnamed: 3': '경찰공무원 정원(B)'}, inplace=True)
residents.rename(columns={'Unnamed: 4': '주민등록인구(A)'}, inplace=True)
residents.rename(columns={'Unnamed: 5': '주민등록인구(A)'}, inplace=True)

# 변경된 DataFrame 출력
residents

# residents 데이터의 0행 삭제
residents.drop(2, inplace=True)
residents

# 새로운 열 추가
residents['연도'] = 2021
residents

# residents 데이터의 0행 삭제
residents.drop(1, inplace=True)
residents

# 인덱스 재정렬
residents.reset_index(drop=True, inplace = True)

# 데이터 확인
residents

"""<br>
<br>
<br>
<br>
<br>
<br>
"""

# 시각화
import matplotlib.pyplot as plt
plt.rc('font', family='NanumBarunGothic')

plt.bar(residents['지역'], residents['경찰공무원 1인당 담당주민수(A/B)'])
plt.xticks(rotation=90)
plt.title('경찰공무원 1인당 담당주민수',fontsize=10) # 타이틀 설정
plt.show()

"""# 범죄발생건수(시도)"""

# 경찰 담당 주민 수 파일 가져오기
import pandas as pd
crime = '/content/drive/MyDrive/2023NABIS공모전/인구 천명당 범죄발생건수(시도)_2021.xlsx'

# CSV 파일 읽어오기
crime = pd.read_excel(crime)

# 가져온 데이터를 확인
crime

# crime 데이터의 0행 삭제
crime.drop(0, inplace=True)

# crime 데이터의 0열 삭제
crime.drop('인구 천명당 범죄발생건수(시도)', axis=1, inplace=True)

# 특정 컬럼의 이름 변경
crime.rename(columns={'Unnamed: 1': '지역'}, inplace=True)
crime.rename(columns={'Unnamed: 2': '범죄발생건수(A)'}, inplace=True)
crime.rename(columns={'Unnamed: 3': '주민등록인구(B)'}, inplace=True)
crime.rename(columns={'Unnamed: 4': '인구 천명당 범죄발생건수(A/B*1000)'}, inplace=True)

# crime 데이터의 0행 삭제
crime.drop(2, inplace=True)

# 새로운 열 추가
crime['연도'] = 2021

# crime 데이터의 0행 삭제
crime.drop(1, inplace=True)

# 인덱스 재정렬
crime.reset_index(drop=True, inplace = True)

# 데이터 확인
crime

# 시각화
import matplotlib.pyplot as plt
plt.rc('font', family='NanumBarunGothic')

plt.bar(crime['지역'], crime['인구 천명당 범죄발생건수(A/B*1000)'])
plt.xticks(rotation=90)
plt.title('인구 천명당 범죄발생건수',fontsize=10) # 타이틀 설정
plt.show()

import matplotlib.pyplot as plt
plt.rc('font', family='NanumBarunGothic')

plt.bar(residents['지역'], residents['경찰공무원 1인당 담당주민수(A/B)'])
plt.plot(crime['지역'], crime['인구 천명당 범죄발생건수(A/B*1000)'], color='red')
plt.xticks(rotation=90)
plt.title('인구 천명당 범죄발생건수',fontsize=10) # 타이틀 설정
plt.show()

fig, ax1 = plt.subplots(figsize=(20, 5))

# 첫 번째 y축 (값1)
color = 'tab:blue'
ax1.set_xlabel('지역')
ax1.set_ylabel('경찰공무원 1인당 담당주민수', color=color)
ax1.bar(residents['지역'], residents['경찰공무원 1인당 담당주민수(A/B)'], color='pink', label='담당주민수')
ax1.tick_params(axis='y', labelcolor=color)

# 두 번째 y축 (값2)
ax2 = ax1.twinx()  # 같은 x축을 공유하는 두 번째 y축
color = 'tab:red'
ax2.set_ylabel('인구 천명당 범죄발생건수', color=color)
ax2.plot(crime['지역'], crime['인구 천명당 범죄발생건수(A/B*1000)'], color='red', label='범죄발생건수')
ax2.tick_params(axis='y', labelcolor=color)

fig.tight_layout()
ax1.legend()
ax2.legend()
plt.show()

"""<br>
<br>
<br>
<br>

# 범죄발생시간
"""

# 파일 가져오기
import pandas as pd
time = '/content/drive/MyDrive/2023NABIS공모전/범죄_발생시간(2021).xlsx'

# CSV 파일 읽어오기
time = pd.read_excel(time)

# 가져온 데이터를 확인
time

# 특정 컬럼의 이름 변경
time.rename(columns={'2021': '계'}, inplace=True)
time.rename(columns={'2021.1': '00:00~02:59'}, inplace=True)
time.rename(columns={'2021.2': '03:00~05:59'}, inplace=True)
time.rename(columns={'2021.3': '06:00~08:59'}, inplace=True)
time.rename(columns={'2021.4': '09:00~11:59'}, inplace=True)
time.rename(columns={'2021.5': '12:00~14:59'}, inplace=True)
time.rename(columns={'2021.6': '15:00~17:59'}, inplace=True)
time.rename(columns={'2021.7': '18:00~20:59'}, inplace=True)
time.rename(columns={'2021.8': '21:00~23:59'}, inplace=True)
time.rename(columns={'2021.9': '미상'}, inplace=True)

# time 데이터의 0행 삭제
time.drop(0, inplace=True)

time

# 새로운 열 추가
time['연도'] = 2021

# 1행 제거
time.drop(1, inplace=True)

# 11행부터 제거
time.drop(range(11, 44), inplace=True)

# 비어있는 열 '강력범죄'로 변경
time.loc[time['죄종별(1)'].isna(), '죄종별(1)'] = '강력범죄'

time

# 인덱스 재정렬
time.reset_index(drop=True, inplace = True)

# 데이터 확인
time

time_2 = time[['00:00~02:59', '03:00~05:59', '06:00~08:59', '09:00~11:59', '12:00~14:59', '15:00~17:59', '18:00~20:59', '21:00~23:59', '미상']]
time_2 = time_2.transpose()
time_2

time_2.rename(columns={0: '합계'}, inplace=True)
time_2

# 인덱스 재정렬
time_2.reset_index(inplace = True)
time_2

# 시각화
import matplotlib.pyplot as plt
plt.rc('font', family='NanumBarunGothic')

plt.subplots(figsize=(20, 5))
plt.bar(time_2['index'], time_2['합계'])
#plt.xticks(rotation=90)
plt.title('범죄발생시간',fontsize=10) # 타이틀 설정
plt.show()

"""<br>
<br>
<br>
<br>

# 범죄발생요일
"""

# 파일 가져오기
import pandas as pd
week = '/content/drive/MyDrive/2023NABIS공모전/범죄_발생요일_2021.xlsx'

# CSV 파일 읽어오기
week = pd.read_excel(week)

# 가져온 데이터를 확인
week

# 특정 컬럼의 이름 변경
week.rename(columns={'2021': '계'}, inplace=True)
week.rename(columns={'2021.1': '일요일'}, inplace=True)
week.rename(columns={'2021.2': '월요일'}, inplace=True)
week.rename(columns={'2021.3': '화요일'}, inplace=True)
week.rename(columns={'2021.4': '수요일'}, inplace=True)
week.rename(columns={'2021.5': '목요일'}, inplace=True)
week.rename(columns={'2021.6': '금요일'}, inplace=True)
week.rename(columns={'2021.7': '토요일'}, inplace=True)

# time 데이터의 0행 삭제
week.drop(0, inplace=True)

week

# 1행 제거
week.drop(1, inplace=True)

# 11행부터 제거
week.drop(range(11, 44), inplace=True)

# 비어있는 열 '강력범죄'로 변경
week.loc[week['죄종별(1)'].isna(), '죄종별(1)'] = '강력범죄'

week

# 인덱스 재정렬
week.reset_index(drop=True, inplace = True)

# 데이터 확인
week

week_2 = week[['일요일', '월요일', '화요일', '수요일', '목요일', '금요일', '토요일']]
week_2 = week_2.transpose()
week_2

week_2.rename(columns={0: '합계'}, inplace=True)
week_2

# 인덱스 재정렬
week_2.reset_index(inplace = True)
week_2

# 시각화
import matplotlib.pyplot as plt
plt.rc('font', family='NanumBarunGothic')

plt.subplots(figsize=(20, 5))
plt.bar(week_2['index'], week_2['합계'])
plt.title('범죄발생요일',fontsize=10) # 타이틀 설정
plt.show()

"""# 범죄발생장소"""

# 파일 가져오기
import pandas as pd
place = '/content/drive/MyDrive/2023NABIS공모전/범죄_발생장소_2021.xlsx'

# CSV 파일 읽어오기
place = pd.read_excel(place)

# 가져온 데이터를 확인
place

# 특정 컬럼의 이름 변경
place.rename(columns=place.iloc[0], inplace=True)

# 데이터의 0행 삭제
place.drop(0, inplace=True)

place

# 1행 제거
place.drop(1, inplace=True)

# 11행부터 제거
place.drop(range(11, 44), inplace=True)

# 비어있는 열 '강력범죄'로 변경
place.loc[place['죄종별(1)'].isna(), '죄종별(1)'] = '강력범죄'

place

# 인덱스 재정렬
place.reset_index(drop=True, inplace = True)

# 데이터 확인
place

place_2 = place.transpose()
place_2

place_2.rename(columns={0: '합계'}, inplace=True)

# 인덱스 재정렬
place_2.reset_index(inplace = True)

place_2.drop(range(0,3), inplace=True)

place_2

place_2 = place_2.astype({'합계':'int32'})
place_2

place_3 = place_2.nlargest(10, '합계', keep='all')
place_3

# 인덱스 재정렬
place_3.reset_index(drop=True, inplace = True)
place_3

# 시각화
import matplotlib.pyplot as plt
plt.rc('font', family='NanumBarunGothic')

plt.subplots(figsize=(20, 5))
plt.bar(place_3['index'], place_3['합계'])
plt.title('범죄발생장소(상위 10개)',fontsize=10) # 타이틀 설정
plt.show()